### ISSUE TITLE
Is this adapter still maintained?  PLEASE RESPOND UNTIL 30.4.2024 latest

### ISSUE THREAD

**Issue by mcm1957** [Marco15453/ioBroker.bayernluft#6]
As you closed you request for addition to our repositories (https://github.com/ioBroker/ioBroker.repositories/pull/1986) and there is no visible activity at this repository since app 2 years please respond and let us know if you will be maintaining this adapter in the future.

If you do not plan to work on this adapter, please let us know if it's ok to move it to the iobroker community area so that other can work on it. Of course you will continue to have write access if you want to have. If you confirm to move please simply transfer the repository ownership to me (@mcm1957) - I will gtransfer ist to the orga immidiatly afterwards.

**Please note, that we might fork and transfer npm to the organisation anyway if there is no reaction until 30.4.2024**

But of course we would prefer to achive consent about the future of this adapter with you.

**Comment by Marco15453** [comment]
# **This Adapter is no longer maintained!**

**Comment by mcm1957** [comment]
@Marco15453 
Thanks for your feedback and THANKS for the work already done by you.

**Comment by Marco15453** [comment]
I have quested a transfer to transfer the repo to you

**Comment by mcm1957** [comment]
Thanks for transfer. I've already moved it to community adapters
